@extends('layouts.app')
@section('title', '予約詳細 | MUSAKO')
@section('content')
@php
    $slot = $reservationRequest->lessonSlot;
    $statusLabel = ['pending' => '承認待ち', 'approved' => '予約確定', 'rejected' => '却下', 'cancelled' => 'キャンセル'][$reservationRequest->status->value];
    $statusClass = ['pending' => 'bg-amber-100 text-amber-900', 'approved' => 'bg-emerald-100 text-emerald-900', 'rejected' => 'bg-red-100 text-red-800', 'cancelled' => 'bg-stone-200 text-stone-600'][$reservationRequest->status->value];
@endphp
<div class="mx-auto max-w-5xl"><a href="{{ route('staff.dashboard', ['view' => 'day', 'date' => $slot->starts_at->format('Y-m-d')]) }}" class="text-sm font-semibold text-amber-700">← カレンダーに戻る</a><div class="mt-4 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p class="text-sm font-semibold tracking-widest text-amber-700">RESERVATION DETAIL</p><h1 class="mt-1 text-2xl font-bold sm:text-3xl">{{ $reservationRequest->studentProfile->user->name }}さんの予約</h1></div><span class="self-start rounded-full px-3 py-1 text-sm font-bold {{ $statusClass }}">{{ $statusLabel }}</span></div>
@if ($errors->any())<div class="mt-5 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800">{{ $errors->first() }}</div>@endif
<div class="mt-6 grid gap-5 lg:grid-cols-[1fr_20rem]"><section class="rounded-2xl border border-stone-200 bg-white p-5 shadow-sm sm:p-7"><h2 class="text-xl font-bold">レッスン情報</h2><dl class="mt-5 grid gap-4 text-sm sm:grid-cols-2"><div><dt class="text-stone-500">生徒</dt><dd class="mt-1 font-semibold">{{ $reservationRequest->studentProfile->user->name }}</dd></div><div><dt class="text-stone-500">日時</dt><dd class="mt-1 font-semibold">{{ $slot->starts_at->format('Y年n月j日 H:i') }}〜{{ $slot->ends_at->format('H:i') }}</dd></div><div><dt class="text-stone-500">講師</dt><dd class="mt-1 font-semibold">{{ $slot->teacherProfile->display_name }}</dd></div><div><dt class="text-stone-500">会場</dt><dd class="mt-1 font-semibold">{{ $slot->venue?->name ?? '会場未定' }}</dd></div><div><dt class="text-stone-500">コース</dt><dd class="mt-1 font-semibold">{{ $slot->course?->name ?? 'コース指定なし' }}</dd></div><div><dt class="text-stone-500">予約状態</dt><dd class="mt-1 font-semibold">{{ $statusLabel }}</dd></div></dl><a href="{{ route('staff.lesson-slots.edit', $slot) }}" class="mt-6 inline-flex min-h-11 items-center rounded-xl border border-stone-300 px-4 text-sm font-bold">レッスン枠を編集</a></section>
<aside class="grid content-start gap-4">@if ($reservationRequest->status->value === 'pending')<form method="post" action="{{ route('staff.reservations.update', $reservationRequest) }}" class="rounded-2xl border border-amber-300 bg-white p-5 shadow-sm">@csrf @method('patch')<h2 class="font-bold">予約を確認</h2><label class="mt-3 grid gap-2 text-sm font-semibold">生徒へのメモ<textarea name="staff_note" rows="3" maxlength="1000" class="rounded-xl border border-stone-300 p-3"></textarea></label><div class="mt-4 grid grid-cols-2 gap-2"><button name="decision" value="rejected" class="min-h-11 rounded-xl border border-red-300 font-bold text-red-700">却下</button><button name="decision" value="approved" class="min-h-11 rounded-xl bg-emerald-600 font-bold text-white">承認</button></div></form>@endif
@if ($reservationRequest->attendanceNotice)<section class="rounded-2xl border {{ $reservationRequest->attendanceNotice->type->value === 'absence' ? 'border-red-200 bg-red-50' : 'border-orange-200 bg-orange-50' }} p-5"><h2 class="font-bold">{{ $reservationRequest->attendanceNotice->type->value === 'absence' ? '欠席連絡' : '遅刻連絡' }}</h2>@if ($reservationRequest->attendanceNotice->late_minutes)<p class="mt-2 text-sm">{{ $reservationRequest->attendanceNotice->late_minutes }}分遅れ</p>@endif @if ($reservationRequest->attendanceNotice->expected_arrival_at)<p class="mt-1 text-sm">到着予定 {{ $reservationRequest->attendanceNotice->expected_arrival_at->format('H:i') }}</p>@endif @if ($reservationRequest->attendanceNotice->notes)<p class="mt-2 text-sm">{{ $reservationRequest->attendanceNotice->notes }}</p>@endif</section>@endif</aside></div>
@if ($reservationRequest->transferRequests->isNotEmpty() || $reservationRequest->resultingTransferRequest)<section class="mt-5 rounded-2xl border border-violet-200 bg-violet-50 p-5"><h2 class="font-bold text-violet-900">振替情報</h2>@foreach ($reservationRequest->transferRequests as $transfer)<p class="mt-2 text-sm">振替先：{{ $transfer->requestedLessonSlot->starts_at->format('Y年n月j日 H:i') }}・{{ ['pending' => '申請中', 'approved' => '承認済み', 'rejected' => '却下'][$transfer->status->value] }}</p>@endforeach @if ($reservationRequest->resultingTransferRequest)<p class="mt-2 text-sm">元予約：{{ $reservationRequest->resultingTransferRequest->originalReservationRequest->lessonSlot->starts_at->format('Y年n月j日 H:i') }}</p>@endif</section>@endif
</div>
@endsection
