@extends('layouts.app')
@section('title', 'スケジュール | MUSAKO')
@section('content')
@php
    $filterQuery = array_filter(['teacher_profile_id' => request('teacher_profile_id'), 'venue_id' => request('venue_id'), 'reservation_status' => request('reservation_status')], fn ($value) => $value !== null && $value !== '');
    $periodLabel = match ($calendarView) { 'week' => $calendarRange->start->format('n/j').'〜'.$calendarRange->end->format('n/j'), 'day' => $calendarRange->focus->format('Y年n月j日'), default => $calendarRange->focus->format('Y年 n月') };
@endphp
<div class="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p class="text-sm font-semibold tracking-widest text-amber-700">STAFF SCHEDULE</p><h1 class="mt-1 text-2xl font-bold sm:text-4xl">レッスンスケジュール</h1><p class="mt-2 text-sm text-stone-600">予約・振替・出欠状況をカレンダーでまとめて確認できます。</p></div><a href="{{ route('staff.lesson-slots.create') }}" class="inline-flex min-h-12 items-center justify-center rounded-xl bg-stone-900 px-5 font-semibold text-white">＋ レッスン枠を作成</a></div>
@if ($errors->any())<div class="mt-5 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800">{{ $errors->first() }}</div>@endif

<section class="mt-6 rounded-2xl border border-stone-200 bg-white p-4 shadow-sm sm:p-5" aria-label="カレンダー操作">
    <form method="get" action="{{ route('staff.dashboard') }}" class="grid gap-3 md:grid-cols-4 lg:grid-cols-5"><input type="hidden" name="view" value="{{ $calendarView }}"><input type="hidden" name="date" value="{{ $calendarRange->focus->format('Y-m-d') }}">
        @if (auth()->user()->role->value === 'admin')<label class="grid gap-1 text-xs font-semibold text-stone-600">講師<select name="teacher_profile_id" class="min-h-11 rounded-xl border border-stone-300 bg-white px-3 text-sm"><option value="">すべての講師</option>@foreach ($teachers as $teacher)<option value="{{ $teacher->id }}" @selected((string) $teacherFilterId === (string) $teacher->id)>{{ $teacher->display_name }}</option>@endforeach</select></label>@else<div class="grid gap-1 text-xs font-semibold text-stone-600"><span>講師</span><div class="flex min-h-11 items-center rounded-xl bg-stone-100 px-3 text-sm">{{ auth()->user()->teacherProfile?->display_name ?? '講師未設定' }}</div></div>@endif
        <label class="grid gap-1 text-xs font-semibold text-stone-600">会場<select name="venue_id" class="min-h-11 rounded-xl border border-stone-300 bg-white px-3 text-sm"><option value="">すべての会場</option>@foreach ($venues as $venue)<option value="{{ $venue->id }}" @selected((string) $venueFilterId === (string) $venue->id)>{{ $venue->name }}</option>@endforeach</select></label>
        <label class="grid gap-1 text-xs font-semibold text-stone-600">予約状態<select name="reservation_status" class="min-h-11 rounded-xl border border-stone-300 bg-white px-3 text-sm"><option value="">すべての状態</option>@foreach (['pending' => '承認待ち', 'approved' => '予約確定', 'rejected' => '却下', 'cancelled' => 'キャンセル'] as $value => $label)<option value="{{ $value }}" @selected($reservationStatus?->value === $value)>{{ $label }}</option>@endforeach</select></label>
        <div class="flex items-end gap-2"><button class="min-h-11 flex-1 rounded-xl bg-amber-400 px-4 text-sm font-bold">絞り込む</button><a href="{{ route('staff.dashboard', ['view' => $calendarView, 'date' => $calendarRange->focus->format('Y-m-d')]) }}" class="inline-flex min-h-11 items-center rounded-xl border border-stone-300 px-3 text-sm">解除</a></div>
    </form>
</section>

<section class="mt-5" aria-labelledby="staff-calendar-title">
    <div class="flex flex-col gap-3 xl:flex-row xl:items-center xl:justify-between">
        <div class="flex items-center gap-2"><a href="{{ route('staff.dashboard', ['view' => $calendarView, 'date' => $calendarRange->previousFocus()->format('Y-m-d'), ...$filterQuery]) }}" class="grid min-h-11 min-w-11 place-items-center rounded-xl border border-stone-300 bg-white" aria-label="前の期間">←</a><h2 id="staff-calendar-title" class="min-w-36 text-center text-xl font-bold">{{ $periodLabel }}</h2><a href="{{ route('staff.dashboard', ['view' => $calendarView, 'date' => $calendarRange->nextFocus()->format('Y-m-d'), ...$filterQuery]) }}" class="grid min-h-11 min-w-11 place-items-center rounded-xl border border-stone-300 bg-white" aria-label="次の期間">→</a><a href="{{ route('staff.dashboard', ['view' => $calendarView, 'date' => today()->format('Y-m-d'), ...$filterQuery]) }}" class="inline-flex min-h-11 items-center rounded-xl border border-stone-300 bg-white px-3 text-sm font-semibold">今日</a></div>
        <div class="grid grid-cols-3 rounded-xl border border-stone-300 bg-white p-1 text-sm font-semibold">@foreach (['month' => '月', 'week' => '週', 'day' => '日'] as $value => $label)<a href="{{ route('staff.dashboard', ['view' => $value, 'date' => $calendarRange->focus->format('Y-m-d'), ...$filterQuery]) }}" class="grid min-h-10 min-w-16 place-items-center rounded-lg {{ $calendarView === $value ? 'bg-stone-900 text-white' : 'hover:bg-stone-100' }}">{{ $label }}表示</a>@endforeach</div>
    </div>

    @if ($calendarView === 'month')
        <div class="mt-4 hidden overflow-hidden rounded-2xl border border-stone-200 bg-white shadow-sm md:block"><div class="grid grid-cols-7 border-b border-stone-200 bg-stone-50 text-center text-xs font-semibold text-stone-500">@foreach (['日','月','火','水','木','金','土'] as $dayName)<div class="py-3">{{ $dayName }}</div>@endforeach</div><div class="grid grid-cols-7">@foreach ($calendarDays as $day) @php($daySlots = $calendarSlotsByDay->get($day->format('Y-m-d'), collect())) <section class="min-h-40 min-w-0 border-b border-r border-stone-100 p-2 {{ $day->month !== $calendarRange->focus->month ? 'bg-stone-50' : '' }}"><div class="flex items-center justify-between"><a href="{{ route('staff.dashboard', ['view' => 'day', 'date' => $day->format('Y-m-d'), ...$filterQuery]) }}" class="text-xs font-bold {{ $day->isToday() ? 'grid size-7 place-items-center rounded-full bg-stone-900 text-white' : '' }}">{{ $day->day }}</a>@if ($day->endOfDay()->isFuture())<a href="{{ route('staff.lesson-slots.create', ['starts_at' => $day->format('Y-m-d').'T10:00']) }}" class="text-base text-stone-400" aria-label="{{ $day->format('n月j日') }}に枠を作成">＋</a>@endif</div><div class="mt-2 grid gap-1.5">@foreach ($daySlots as $slot) @include('staff.calendar._slot', ['slot' => $slot, 'compact' => true]) @endforeach</div></section> @endforeach</div></div>
    @else
        <div class="mt-4 hidden overflow-x-auto rounded-2xl border border-stone-200 bg-white shadow-sm md:block">
            @if ($calendarView === 'week')
                <div class="min-w-[72rem]"><div class="grid grid-cols-[4rem_repeat(7,minmax(8rem,1fr))] border-b border-stone-200 bg-stone-50"><div></div>@foreach ($calendarDays as $day)<a href="{{ route('staff.dashboard', ['view' => 'day', 'date' => $day->format('Y-m-d'), ...$filterQuery]) }}" class="border-l border-stone-200 py-3 text-center text-sm font-bold">{{ $day->format('n/j') }}<span class="ml-1 text-xs text-stone-400">{{ ['日','月','火','水','木','金','土'][$day->dayOfWeek] }}</span></a>@endforeach</div>@foreach ($timelineHours as $hour)<div class="grid min-h-24 grid-cols-[4rem_repeat(7,minmax(8rem,1fr))] border-b border-stone-100"><div class="pr-2 pt-2 text-right text-xs font-semibold text-stone-400">{{ sprintf('%02d:00', $hour) }}</div>@foreach ($calendarDays as $day) @php($hourSlots = $calendarSlotsByDay->get($day->format('Y-m-d'), collect())->filter(fn ($slot) => $slot->starts_at->hour === $hour)) <div class="min-w-0 border-l border-stone-100 p-1.5"><a href="{{ route('staff.lesson-slots.create', ['starts_at' => $day->format('Y-m-d').'T'.sprintf('%02d:00', $hour)]) }}" class="block text-right text-xs text-stone-300" aria-label="この時間に枠を作成">＋</a><div class="grid gap-1">@foreach ($hourSlots as $slot) @include('staff.calendar._slot', ['slot' => $slot, 'compact' => true]) @endforeach</div></div> @endforeach</div>@endforeach</div>
            @else
                <div>@foreach ($timelineHours as $hour) @php($hourSlots = $calendarSlotsByDay->get($calendarRange->focus->format('Y-m-d'), collect())->filter(fn ($slot) => $slot->starts_at->hour === $hour)) <div class="grid min-h-24 grid-cols-[4rem_1fr] border-b border-stone-100"><div class="pr-2 pt-3 text-right text-xs font-semibold text-stone-400">{{ sprintf('%02d:00', $hour) }}</div><div class="border-l border-stone-100 p-2"><a href="{{ route('staff.lesson-slots.create', ['starts_at' => $calendarRange->focus->format('Y-m-d').'T'.sprintf('%02d:00', $hour)]) }}" class="block text-right text-xs font-semibold text-stone-300">＋ この時間に枠作成</a><div class="grid gap-2 lg:grid-cols-2">@foreach ($hourSlots as $slot) @include('staff.calendar._slot', ['slot' => $slot, 'compact' => false]) @endforeach</div></div></div> @endforeach</div>
            @endif
        </div>
    @endif

    <div class="mt-4 md:hidden">
        @if ($calendarView === 'month')<div class="rounded-2xl border border-stone-200 bg-white p-3 shadow-sm"><div class="grid grid-cols-7 text-center text-[11px] font-semibold text-stone-400">@foreach (['日','月','火','水','木','金','土'] as $dayName)<span class="py-1">{{ $dayName }}</span>@endforeach</div><div class="mt-1 grid grid-cols-7 gap-1">@foreach ($calendarDays as $day)<a href="{{ route('staff.dashboard', ['view' => 'day', 'date' => $day->format('Y-m-d'), ...$filterQuery]) }}" class="relative grid min-h-11 place-items-center rounded-xl text-sm font-semibold {{ $day->isToday() ? 'bg-stone-900 text-white' : ($day->month === $calendarRange->focus->month ? 'hover:bg-stone-100' : 'text-stone-300') }}">{{ $day->day }}@if ($calendarSlotsByDay->has($day->format('Y-m-d')))<span class="absolute bottom-1 size-1 rounded-full bg-amber-500"></span>@endif</a>@endforeach</div></div><p class="mt-3 text-center text-sm text-stone-500">日付を選ぶと当日の時間割を表示します。</p>
        @else<div class="grid gap-5">@forelse ($calendarSlotsByDay as $date => $daySlots)<section><div class="flex items-center justify-between"><h3 class="font-bold">{{ $daySlots->first()->starts_at->format('n月j日') }}（{{ ['日','月','火','水','木','金','土'][$daySlots->first()->starts_at->dayOfWeek] }}）</h3><a href="{{ route('staff.lesson-slots.create', ['starts_at' => $date.'T10:00']) }}" class="text-sm font-semibold text-amber-700">＋ 枠作成</a></div><div class="mt-2 grid gap-3">@foreach ($daySlots as $slot) @include('staff.calendar._slot', ['slot' => $slot, 'compact' => false]) @endforeach</div></section>@empty<div class="rounded-2xl border border-dashed border-stone-300 bg-white p-10 text-center text-stone-500">この期間のレッスン枠はありません。</div>@endforelse</div>@endif
    </div>
</section>

<div class="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><a href="{{ route('staff.reservations.index') }}" class="rounded-2xl bg-amber-400 p-5 shadow-sm"><span class="text-sm font-semibold">予約の承認待ち</span><strong class="mt-1 block text-3xl">{{ $pendingCount }}</strong></a><a href="{{ route('staff.transfer-requests.index') }}" class="rounded-2xl border border-emerald-200 bg-emerald-50 p-5 shadow-sm"><span class="text-sm text-emerald-800">振替の承認待ち</span><strong class="mt-1 block text-3xl">{{ $pendingTransferCount }}</strong></a><a href="{{ route('staff.membership-status-requests.index') }}" class="rounded-2xl border border-sky-200 bg-sky-50 p-5 shadow-sm"><span class="text-sm text-sky-800">在籍申請の承認待ち</span><strong class="mt-1 block text-3xl">{{ $pendingMembershipCount }}</strong></a><a href="{{ route('staff.procedure-requests.index') }}" class="rounded-2xl border border-violet-200 bg-violet-50 p-5 shadow-sm"><span class="text-sm text-violet-800">各種手続きの承認待ち</span><strong class="mt-1 block text-3xl">{{ $pendingProcedureCount }}</strong></a><a href="{{ route('staff.inquiries.index') }}" class="rounded-2xl border border-orange-200 bg-orange-50 p-5 shadow-sm"><span class="text-sm text-orange-800">未解決のお問い合わせ</span><strong class="mt-1 block text-3xl">{{ $openInquiryCount }}</strong></a><a href="{{ route('staff.lesson-slots.index') }}" class="rounded-2xl border border-stone-200 bg-white p-5 shadow-sm"><span class="text-sm text-stone-500">今後のレッスン枠</span><strong class="mt-1 block text-3xl">{{ $upcomingSlotCount }}</strong></a></div>

<section class="mt-8"><div class="flex items-center justify-between"><h2 class="text-xl font-bold">本日のお休み・遅刻</h2><span class="rounded-full bg-stone-200 px-3 py-1 text-xs font-semibold">{{ $todayNotices->count() }}件</span></div><div class="mt-4 grid gap-3 sm:grid-cols-2">@forelse ($todayNotices as $notice)<a href="{{ route('staff.reservations.show', $notice->reservationRequest) }}" class="rounded-2xl border border-stone-200 bg-white p-4 shadow-sm"><div class="flex items-center justify-between gap-3"><strong>{{ $notice->reservationRequest->studentProfile->user->name }}</strong><span class="rounded-full {{ $notice->type->value === 'absence' ? 'bg-red-100 text-red-700' : 'bg-amber-100 text-amber-800' }} px-3 py-1 text-xs font-semibold">{{ $notice->type->value === 'absence' ? 'お休み' : '遅刻' }}</span></div><p class="mt-2 text-sm font-semibold">{{ $notice->reservationRequest->lessonSlot->starts_at->format('H:i') }}〜{{ $notice->reservationRequest->lessonSlot->ends_at->format('H:i') }}</p>@if ($notice->late_minutes || $notice->expected_arrival_at)<p class="mt-1 text-sm text-stone-600">{{ $notice->late_minutes ? $notice->late_minutes.'分遅れ' : '' }}{{ $notice->expected_arrival_at ? ' 到着予定 '.$notice->expected_arrival_at->format('H:i') : '' }}</p>@endif @if ($notice->notes)<p class="mt-2 text-sm text-stone-500">{{ $notice->notes }}</p>@endif</a>@empty<div class="rounded-2xl border border-dashed border-stone-300 bg-white p-8 text-center text-stone-500 sm:col-span-2">本日の連絡はありません。</div>@endforelse</div></section>
@endsection
