@extends('layouts.app')
@section('title', '料金設定 | MUSAKO')
@section('content')
<div><p class="text-sm font-semibold tracking-widest text-amber-700">PRICING SETTINGS</p><h1 class="mt-1 text-2xl font-bold sm:text-3xl">料金設定</h1><p class="mt-2 text-sm text-stone-600">料金を上書きせず、適用開始日ごとの履歴として管理します。</p></div>
@if ($errors->any())<div class="mt-5 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800">{{ $errors->first() }}</div>@endif

@if ($canManage)
<div class="mt-7 grid gap-5 lg:grid-cols-2">
    <section class="rounded-2xl border border-stone-200 bg-white p-5 shadow-sm"><h2 class="text-xl font-bold">新しい料金を登録</h2><form method="post" action="{{ route('staff.pricing-settings.rates.store') }}" class="mt-5 grid gap-4 sm:grid-cols-2">@csrf<label class="grid gap-2 text-sm font-semibold sm:col-span-2">料金項目<select name="kind" required class="min-h-12 rounded-xl border border-stone-300 bg-white px-3">@foreach (App\Enums\PriceRateKind::cases() as $kind)<option value="{{ $kind->value }}">{{ $kind->label() }}</option>@endforeach</select></label><label class="grid gap-2 text-sm font-semibold">料金区分<select name="pricing_category" class="min-h-12 rounded-xl border border-stone-300 bg-white px-3"><option value="">その他料金では未選択</option>@foreach (App\Enums\PricingCategory::cases() as $category)<option value="{{ $category->value }}">{{ $category->label() }}</option>@endforeach</select></label><label class="grid gap-2 text-sm font-semibold">月回数<input type="number" name="monthly_lesson_count" min="1" max="31" class="min-h-12 rounded-xl border border-stone-300 px-3" placeholder="レギュラーのみ"></label><label class="grid gap-2 text-sm font-semibold">金額（税込）<input type="number" name="amount" min="0" max="10000000" required class="min-h-12 rounded-xl border border-stone-300 px-3"></label><label class="grid gap-2 text-sm font-semibold">適用開始日<input type="date" name="effective_from" required class="min-h-12 rounded-xl border border-stone-300 px-3"></label><button class="min-h-12 rounded-xl bg-stone-900 px-5 font-bold text-white sm:col-span-2">料金履歴を追加</button></form></section>
    <section class="rounded-2xl border border-stone-200 bg-white p-5 shadow-sm"><h2 class="text-xl font-bold">表示・入会金設定を登録</h2><form method="post" action="{{ route('staff.pricing-settings.configuration.store') }}" class="mt-5 grid gap-4 sm:grid-cols-2">@csrf<label class="grid gap-2 text-sm font-semibold">適用開始日<input type="date" name="effective_from" required class="min-h-12 rounded-xl border border-stone-300 px-3"></label><label class="grid gap-2 text-sm font-semibold">公開表示モード<select name="display_mode" required class="min-h-12 rounded-xl border border-stone-300 bg-white px-3">@foreach (App\Enums\PricingDisplayMode::cases() as $mode)<option value="{{ $mode->value }}">{{ $mode->label() }}</option>@endforeach</select></label><label class="grid gap-2 text-sm font-semibold">通常入会金<input type="number" name="normal_admission_fee" min="0" class="min-h-12 rounded-xl border border-stone-300 px-3"></label><label class="grid gap-2 text-sm font-semibold">キャンペーン料金<input type="number" name="admission_campaign_fee" min="0" class="min-h-12 rounded-xl border border-stone-300 px-3"></label><label class="flex items-center gap-2 text-sm font-semibold sm:col-span-2"><input type="checkbox" name="admission_campaign_enabled" value="1">入会金キャンペーンを有効にする</label><label class="grid gap-2 text-sm font-semibold sm:col-span-2">キャンペーン表示文言<input name="admission_campaign_message" maxlength="255" class="min-h-12 rounded-xl border border-stone-300 px-3"></label><label class="grid gap-2 text-sm font-semibold sm:col-span-2">料金ページ注意書き<textarea name="pricing_notice" rows="3" maxlength="2000" class="rounded-xl border border-stone-300 p-3"></textarea></label><label class="grid gap-2 text-sm font-semibold sm:col-span-2">レッスン料金確認URL<input type="url" name="lesson_pricing_url" maxlength="2048" class="min-h-12 min-w-0 rounded-xl border border-stone-300 px-3"></label><label class="grid gap-2 text-sm font-semibold sm:col-span-2">スタジオ料金確認URL<input type="url" name="studio_pricing_url" maxlength="2048" class="min-h-12 min-w-0 rounded-xl border border-stone-300 px-3"></label><button class="min-h-12 rounded-xl bg-stone-900 px-5 font-bold text-white sm:col-span-2">表示設定履歴を追加</button></form></section>
</div>
@else
<div class="mt-6 rounded-xl border border-sky-200 bg-sky-50 p-4 text-sm text-sky-900">先生アカウントでは料金履歴を確認できます。変更は管理者のみ可能です。</div>
@endif

<section class="mt-9"><div class="flex flex-wrap items-end justify-between gap-2"><h2 class="text-xl font-bold">料金履歴</h2><span class="text-xs text-stone-500">現在・将来予定・過去をすべて保持</span></div><div class="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">@forelse ($rates as $rate) @php($isFuture = $rate->effective_from->isFuture()) @php($isCurrent = $currentRateIds->contains($rate->id)) <article class="min-w-0 rounded-2xl border {{ $isCurrent ? 'border-emerald-300' : 'border-stone-200' }} bg-white p-4 shadow-sm"><div class="flex flex-wrap items-center justify-between gap-2"><strong>{{ $rate->kind->label() }}</strong><span class="rounded-full px-2 py-1 text-xs font-bold {{ $isFuture ? 'bg-sky-100 text-sky-800' : ($isCurrent ? 'bg-emerald-100 text-emerald-800' : 'bg-stone-100 text-stone-600') }}">{{ $isFuture ? '将来予定' : ($isCurrent ? '現在有効' : '過去') }}</span></div><p class="mt-3 text-2xl font-bold">¥{{ number_format($rate->amount) }}</p><p class="mt-2 text-sm text-stone-600">{{ $rate->pricing_category?->label() }} @if ($rate->monthly_lesson_count)・月{{ $rate->monthly_lesson_count }}回@endif</p><p class="mt-2 text-xs text-stone-500">{{ $rate->effective_from->format('Y年n月j日') }}から</p></article>@empty<p class="rounded-2xl border border-dashed border-stone-300 p-8 text-sm text-stone-500 sm:col-span-2 lg:col-span-3">料金履歴はありません。</p>@endforelse</div></section>

<section class="mt-9"><h2 class="text-xl font-bold">表示・入会金設定履歴</h2><div class="mt-4 grid gap-3 lg:grid-cols-2">@forelse ($settings as $setting) @php($isFuture = $setting->effective_from->isFuture()) @php($isCurrent = $currentSettingId === $setting->id) <article class="min-w-0 rounded-2xl border {{ $isCurrent ? 'border-emerald-300' : 'border-stone-200' }} bg-white p-4 shadow-sm"><div class="flex flex-wrap items-center justify-between gap-2"><strong>{{ $setting->display_mode->label() }}</strong><span class="rounded-full px-2 py-1 text-xs font-bold {{ $isFuture ? 'bg-sky-100 text-sky-800' : ($isCurrent ? 'bg-emerald-100 text-emerald-800' : 'bg-stone-100 text-stone-600') }}">{{ $isFuture ? '将来予定' : ($isCurrent ? '現在有効' : '過去') }}</span></div><dl class="mt-3 grid grid-cols-2 gap-3 text-sm"><div><dt class="text-stone-500">通常入会金</dt><dd class="font-semibold">{{ $setting->normal_admission_fee === null ? '未設定' : '¥'.number_format($setting->normal_admission_fee) }}</dd></div><div><dt class="text-stone-500">キャンペーン</dt><dd class="font-semibold">{{ $setting->admission_campaign_enabled ? '有効' : '無効' }}</dd></div></dl><p class="mt-3 break-words text-sm text-stone-600">{{ $setting->admission_campaign_message }}</p><p class="mt-2 text-xs text-stone-500">{{ $setting->effective_from->format('Y年n月j日') }}から</p></article>@empty<p class="rounded-2xl border border-dashed border-stone-300 p-8 text-sm text-stone-500 lg:col-span-2">表示設定履歴はありません。</p>@endforelse</div></section>
@endsection
