@extends('layouts.app')
@section('title', '在籍に関する申請 | MUSAKO')
@section('content')
<div><p class="text-sm font-semibold text-amber-700">MEMBERSHIP</p><h1 class="text-2xl font-bold sm:text-3xl">休会・退会・再開申請</h1><p class="mt-2 text-sm text-stone-600">希望日と理由を入力して申請してください。</p></div>
@if ($errors->any())<div class="mt-5 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800">{{ $errors->first() }}</div>@endif
<div class="mt-6 grid gap-6 lg:grid-cols-[minmax(0,2fr)_minmax(18rem,1fr)]">
    <section id="application-form" class="rounded-2xl border border-stone-200 bg-white p-5 shadow-sm sm:p-6"><h2 class="text-xl font-bold">新しい申請</h2><form method="post" action="{{ route('student.membership-status-requests.store') }}" class="mt-5 grid gap-5">@csrf<div class="grid gap-4 sm:grid-cols-2"><label class="grid gap-2 text-sm font-semibold">申請内容<select name="type" required class="min-h-12 rounded-xl border border-stone-300 bg-white px-3"><option value="pause" @selected(old('type', $selectedType->value) === 'pause')>休会</option><option value="withdraw" @selected(old('type', $selectedType->value) === 'withdraw')>退会</option><option value="resume" @selected(old('type', $selectedType->value) === 'resume')>再開</option></select></label><label class="grid gap-2 text-sm font-semibold">希望日<input type="date" name="effective_on" min="{{ today()->toDateString() }}" value="{{ old('effective_on', today()->addMonth()->toDateString()) }}" required class="min-h-12 rounded-xl border border-stone-300 px-3"></label></div><label class="grid gap-2 text-sm font-semibold">理由（任意）<textarea name="reason" rows="3" maxlength="1000" class="rounded-xl border border-stone-300 p-3 font-normal">{{ old('reason') }}</textarea></label><label class="grid gap-2 text-sm font-semibold">備考（任意）<textarea name="student_note" rows="3" maxlength="1000" class="rounded-xl border border-stone-300 p-3 font-normal">{{ old('student_note') }}</textarea></label><button class="min-h-12 rounded-xl bg-amber-400 px-6 font-bold text-stone-900 sm:justify-self-end">申請する</button></form></section>
    <aside class="rounded-2xl bg-stone-900 p-5 text-white shadow-sm"><h2 class="font-bold">現在の在籍契約</h2><div class="mt-4 grid gap-3">@forelse ($enrollments as $enrollment)<div class="rounded-xl bg-white/10 p-3"><strong class="block text-sm">{{ $enrollment->course->name }}</strong><span class="mt-1 block text-xs text-stone-300">{{ ['pending' => '手続き中', 'active' => '在籍中', 'paused' => '休会中', 'ended' => '終了'][$enrollment->status->value] }}</span></div>@empty<p class="text-sm text-stone-300">在籍契約がありません。</p>@endforelse</div></aside>
</div>
<section class="mt-8"><h2 class="text-xl font-bold">申請履歴</h2><div class="mt-4 grid gap-3">@forelse ($membershipStatusRequests as $membershipStatusRequest)<article class="rounded-2xl border border-stone-200 bg-white p-4 shadow-sm"><div class="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between"><div class="flex flex-wrap items-center gap-2"><strong>{{ ['pause' => '休会', 'withdraw' => '退会', 'resume' => '再開'][$membershipStatusRequest->type->value] }}</strong><span class="rounded-full px-3 py-1 text-xs font-semibold {{ ['pending' => 'bg-amber-100 text-amber-800', 'approved' => 'bg-emerald-100 text-emerald-800', 'rejected' => 'bg-red-100 text-red-700'][$membershipStatusRequest->status->value] }}">{{ ['pending' => '承認待ち', 'approved' => '承認済み', 'rejected' => '却下'][$membershipStatusRequest->status->value] }}</span><span class="text-sm text-stone-600">希望日 {{ $membershipStatusRequest->effective_on->format('Y/m/d') }}</span></div><span class="text-xs text-stone-500">{{ $membershipStatusRequest->applied_at ? '在籍へ反映済み' : ($membershipStatusRequest->status->value === 'approved' ? '反映予定' : '') }}</span></div>@if ($membershipStatusRequest->staff_note)<p class="mt-2 text-sm text-stone-500">担当者から: {{ $membershipStatusRequest->staff_note }}</p>@endif</article>@empty<div class="rounded-2xl border border-dashed border-stone-300 bg-white p-8 text-center text-stone-500">申請履歴はありません。</div>@endforelse</div><div class="mt-6">{{ $membershipStatusRequests->links() }}</div></section>
@endsection
