@extends('layouts.app')
@section('title', '請求詳細 | MUSAKO')
@section('content')
<a href="{{ route('staff.invoices.index', ['month' => $invoice->billing_month->format('Y-m')]) }}" class="text-sm font-semibold text-amber-700">← 請求一覧</a>
<div class="mt-4 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p class="text-sm font-semibold tracking-widest text-amber-700">INVOICE</p><h1 class="text-2xl font-bold sm:text-4xl">{{ $invoice->studentProfile->user->name }}さん</h1><p class="mt-1 text-sm text-stone-500">{{ $invoice->billing_month->format('Y年n月') }} · {{ $invoice->invoice_number ?? '下書き' }}</p></div><div class="rounded-2xl bg-stone-900 px-6 py-4 text-white"><span class="text-xs text-stone-300">請求額</span><strong class="block text-3xl">¥{{ number_format($invoice->total_amount) }}</strong><span class="text-xs">残額 ¥{{ number_format($invoice->remaining_amount) }}</span></div></div>
@if ($errors->any())<div class="mt-5 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800">{{ $errors->first() }}</div>@endif
@if ($invoice->requires_review)<div class="mt-5 rounded-2xl border border-amber-300 bg-amber-50 p-4"><strong>管理者確認が必要です</strong><ul class="mt-2 list-disc space-y-1 pl-5 text-sm">@foreach ($invoice->warnings ?? [] as $warning)<li>{{ $warning }}</li>@endforeach</ul></div>@endif

<section class="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div class="rounded-2xl border border-stone-200 bg-white p-4"><span class="text-xs text-stone-500">請求状態</span><strong class="mt-1 block">{{ $invoice->status->label() }}</strong></div><div class="rounded-2xl border border-stone-200 bg-white p-4"><span class="text-xs text-stone-500">入金状態</span><strong class="mt-1 block">{{ $invoice->payment_status->label() }}{{ $invoice->is_overdue ? '（期限超過）' : '' }}</strong></div><div class="rounded-2xl border border-stone-200 bg-white p-4"><span class="text-xs text-stone-500">支払期限</span><strong class="mt-1 block">{{ $invoice->due_on?->format('Y年n月j日') ?? '未設定' }}</strong></div><div class="rounded-2xl border border-stone-200 bg-white p-4"><span class="text-xs text-stone-500">支払方法</span><strong class="mt-1 block">{{ $invoice->payment_method?->label() ?? '未設定' }}</strong></div></section>

<section class="mt-7 rounded-2xl border border-stone-200 bg-white p-5"><h2 class="text-xl font-bold">請求明細</h2><div class="mt-4 grid gap-2">@foreach ($invoice->items as $item)<div class="flex min-w-0 items-start justify-between gap-4 border-b border-stone-100 py-3 last:border-0"><div class="min-w-0"><strong class="break-words text-sm">{{ $item->description }}</strong>@if ($item->reason)<p class="mt-1 break-words text-xs text-stone-500">理由：{{ $item->reason }} · {{ $item->creator?->name }}</p>@endif</div><span class="shrink-0 font-semibold {{ $item->amount < 0 ? 'text-red-700' : '' }}">{{ $item->amount < 0 ? '-' : '' }}¥{{ number_format(abs($item->amount)) }}</span></div>@endforeach</div><dl class="mt-4 ml-auto grid max-w-sm gap-2 text-sm"><div class="flex justify-between"><dt>自動計算小計</dt><dd>¥{{ number_format($invoice->subtotal) }}</dd></div><div class="flex justify-between"><dt>手動調整</dt><dd>¥{{ number_format($invoice->adjustments_total) }}</dd></div><div class="flex justify-between border-t pt-2 text-lg font-bold"><dt>合計</dt><dd>¥{{ number_format($invoice->total_amount) }}</dd></div></dl></section>

<section class="mt-7 grid gap-5 lg:grid-cols-2"><div class="rounded-2xl border border-stone-200 bg-white p-5"><h2 class="text-xl font-bold">入金履歴</h2><div class="mt-3 grid gap-3">@forelse ($invoice->paymentRecords as $payment)<div class="rounded-xl bg-stone-50 p-3"><div class="flex justify-between gap-3"><strong>¥{{ number_format($payment->amount) }}</strong><span class="text-sm">{{ $payment->paid_on->format('Y/n/j') }}</span></div><p class="mt-1 break-words text-xs text-stone-500">{{ $payment->payment_method->label() }}{{ $payment->external_payment_provider ? ' · '.$payment->external_payment_provider : '' }}{{ $payment->external_payment_reference ? ' · 参照: '.$payment->external_payment_reference : '' }}</p></div>@empty<p class="text-sm text-stone-500">入金はまだありません。</p>@endforelse</div></div><div class="rounded-2xl border border-stone-200 bg-white p-5"><h2 class="text-xl font-bold">契約・料金スナップショット</h2><div class="mt-3 grid gap-3">@foreach ($invoice->pricing_snapshot ?? [] as $snapshot)<div class="rounded-xl bg-stone-50 p-3 text-sm"><strong>{{ $snapshot['course_name'] ?? 'コース' }}</strong><p class="mt-1 text-stone-600">{{ $snapshot['lesson_type'] }} / {{ $snapshot['pricing_category'] }} / 月{{ $snapshot['monthly_lesson_count'] }}回</p><p class="mt-1">基本 ¥{{ number_format($snapshot['base_lesson_fee'] ?? 0) }} · 加算 ¥{{ number_format($snapshot['flex_surcharge'] ?? 0) }}</p></div>@endforeach</div></div></section>

@if ($canManage && $invoice->status === \App\Enums\MonthlyInvoiceStatus::Draft)
<section class="mt-7 grid gap-5 lg:grid-cols-2"><form method="post" action="{{ route('staff.invoices.adjustments.store', $invoice) }}" class="rounded-2xl border border-stone-200 bg-white p-5">@csrf<h2 class="font-bold">追加料金・値引き・調整</h2><div class="mt-3 grid gap-3"><input name="description" required maxlength="255" placeholder="例：教材費／キャンペーン値引き" class="min-h-11 min-w-0 rounded-xl border-stone-300"><input type="number" name="amount" required placeholder="金額（値引きはマイナス）" class="min-h-11 min-w-0 rounded-xl border-stone-300"><textarea name="reason" required maxlength="2000" placeholder="調整理由" class="min-h-24 min-w-0 rounded-xl border-stone-300"></textarea><button class="min-h-11 rounded-xl border border-stone-300 font-semibold">調整を追加</button></div></form><form method="post" action="{{ route('staff.invoices.confirm', $invoice) }}" class="rounded-2xl border border-emerald-200 bg-emerald-50 p-5">@csrf<h2 class="font-bold">請求を確定</h2><p class="mt-2 text-sm text-stone-600">確定後は明細と金額を変更できません。生徒マイページへ公開されます。</p>@if ($invoice->requires_review)<label class="mt-4 flex items-start gap-2 text-sm"><input type="checkbox" name="acknowledge_warnings" value="1" required>警告を確認し、管理者判断でこの金額を確定します</label>@endif<button class="mt-4 min-h-11 w-full rounded-xl bg-emerald-700 px-5 font-semibold text-white">請求を確定する</button></form></section>
@endif

@if ($canManage && $invoice->status === \App\Enums\MonthlyInvoiceStatus::Confirmed)
<section class="mt-7 grid gap-5 lg:grid-cols-2"><form method="post" action="{{ route('staff.invoices.payments.store', $invoice) }}" class="rounded-2xl border border-emerald-200 bg-emerald-50 p-5">@csrf<input type="hidden" name="idempotency_key" value="{{ $paymentIdempotencyKey }}"><h2 class="font-bold">入金登録</h2><p class="mt-1 text-xs text-stone-600">カード番号・口座番号は入力・保存しないでください。</p><div class="mt-3 grid gap-3 sm:grid-cols-2"><label class="text-sm">金額<input type="number" name="amount" min="1" max="{{ $invoice->remaining_amount }}" value="{{ $invoice->remaining_amount }}" required class="mt-1 min-h-11 w-full rounded-xl border-stone-300"></label><label class="text-sm">支払日<input type="date" name="paid_on" value="{{ today()->format('Y-m-d') }}" required class="mt-1 min-h-11 w-full rounded-xl border-stone-300"></label><label class="text-sm">支払方法<select name="payment_method" class="mt-1 min-h-11 w-full rounded-xl border-stone-300">@foreach ($paymentMethods as $method)<option value="{{ $method->value }}">{{ $method->label() }}</option>@endforeach</select></label><label class="text-sm">外部決済サービス<input name="external_payment_provider" maxlength="80" placeholder="例：Stripe" class="mt-1 min-h-11 w-full rounded-xl border-stone-300"></label><label class="text-sm sm:col-span-2">外部参照ID<input name="external_payment_reference" maxlength="191" class="mt-1 min-h-11 w-full rounded-xl border-stone-300"></label><label class="text-sm sm:col-span-2">備考<textarea name="notes" maxlength="2000" class="mt-1 min-h-20 w-full rounded-xl border-stone-300"></textarea></label></div><button class="mt-4 min-h-11 w-full rounded-xl bg-emerald-700 font-semibold text-white">入金を登録</button></form>@if ($invoice->paymentRecords->isEmpty())<form method="post" action="{{ route('staff.invoices.cancel', $invoice) }}" class="rounded-2xl border border-red-200 bg-red-50 p-5">@csrf<h2 class="font-bold">請求を取り消す</h2><p class="mt-2 text-sm text-stone-600">確定内容は削除せず、取消理由と履歴を残します。</p><textarea name="reason" required maxlength="2000" class="mt-4 min-h-24 w-full rounded-xl border-stone-300" placeholder="取消理由"></textarea><button class="mt-3 min-h-11 rounded-xl border border-red-300 px-5 font-semibold text-red-800">履歴を残して取消</button></form>@endif</section>
@endif

<section class="mt-7 rounded-2xl border border-stone-200 bg-white p-5"><h2 class="text-xl font-bold">監査履歴</h2><div class="mt-3 grid gap-2 text-sm">@foreach ($invoice->audits as $audit)<div class="flex flex-col gap-1 border-b border-stone-100 py-2 sm:flex-row sm:justify-between"><span>{{ $audit->event }} · {{ $audit->actor?->name ?? 'システム' }}</span><time class="text-xs text-stone-500">{{ $audit->created_at->format('Y/n/j H:i') }}</time></div>@endforeach</div></section>
@endsection
