@extends('layouts.app')
@section('title', '振替申請詳細 | MUSAKO')
@section('content')
<div class="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p class="text-sm font-semibold text-amber-700">TRANSFER DETAIL</p><h1 class="text-2xl font-bold sm:text-3xl">{{ $transferRequest->studentProfile->user->name }}さんの振替申請</h1></div><a href="{{ route('staff.transfer-requests.index') }}" class="text-sm font-semibold text-stone-600">← 一覧へ</a></div>
@if ($errors->any())<div class="mt-5 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800">{{ $errors->first() }}</div>@endif
<div class="mt-6 grid gap-4 md:grid-cols-2"><section class="rounded-2xl border border-stone-200 bg-white p-5 shadow-sm"><span class="text-xs font-semibold text-stone-500">元の予約</span><h2 class="mt-2 text-lg font-bold">{{ $transferRequest->originalReservationRequest->lessonSlot->starts_at->format('Y年n月j日 H:i') }}</h2><p class="mt-2 text-sm text-stone-600">{{ $transferRequest->originalReservationRequest->lessonSlot->teacherProfile->display_name }} · {{ $transferRequest->originalReservationRequest->lessonSlot->venue?->name ?? '会場未定' }}</p></section><section class="rounded-2xl border border-amber-300 bg-amber-50 p-5 shadow-sm"><span class="text-xs font-semibold text-amber-800">希望する振替先</span><h2 class="mt-2 text-lg font-bold">{{ $transferRequest->requestedLessonSlot->starts_at->format('Y年n月j日 H:i') }}</h2><p class="mt-2 text-sm text-stone-600">{{ $transferRequest->requestedLessonSlot->teacherProfile->display_name }} · {{ $transferRequest->requestedLessonSlot->venue?->name ?? '会場未定' }}</p></section></div>
<section class="mt-4 rounded-2xl border border-stone-200 bg-white p-5 shadow-sm"><dl class="grid gap-4 text-sm sm:grid-cols-2"><div><dt class="text-stone-500">理由</dt><dd class="mt-1">{{ $transferRequest->reason ?: '未入力' }}</dd></div><div><dt class="text-stone-500">備考</dt><dd class="mt-1">{{ $transferRequest->student_note ?: '未入力' }}</dd></div></dl></section>
@if ($transferRequest->status->value === 'pending')<form method="post" action="{{ route('staff.transfer-requests.update', $transferRequest) }}" class="mt-5 grid gap-3 rounded-2xl border border-stone-200 bg-white p-5 shadow-sm sm:grid-cols-[1fr_auto_auto]">@csrf @method('patch')<input name="staff_note" maxlength="1000" placeholder="生徒へのメモ（任意）" class="min-h-12 rounded-xl border border-stone-300 px-3"><button name="decision" value="rejected" class="min-h-12 rounded-xl border border-red-200 px-5 font-semibold text-red-700">却下</button><button name="decision" value="approved" class="min-h-12 rounded-xl bg-emerald-600 px-6 font-semibold text-white">承認</button></form>@else<div class="mt-5 rounded-2xl bg-stone-100 p-5 text-sm"><strong>{{ $transferRequest->status->value === 'approved' ? '承認済み' : '却下' }}</strong><p class="mt-1 text-stone-600">{{ $transferRequest->reviewer?->name }} · {{ $transferRequest->reviewed_at?->format('Y/m/d H:i') }}</p>@if ($transferRequest->staff_note)<p class="mt-2">{{ $transferRequest->staff_note }}</p>@endif</div>@endif
@endsection
