@extends('layouts.app')
@section('title', '予約詳細 | MUSAKO')
@section('content')
@php
    $slot = $reservationRequest->lessonSlot;
    $statusLabel = ['pending' => '予約申請中', 'approved' => '予約確定', 'rejected' => '却下', 'cancelled' => 'キャンセル済み'][$reservationRequest->status->value];
    $statusClass = ['pending' => 'bg-amber-100 text-amber-900', 'approved' => 'bg-emerald-100 text-emerald-900', 'rejected' => 'bg-red-100 text-red-800', 'cancelled' => 'bg-stone-200 text-stone-600'][$reservationRequest->status->value];
@endphp
<div class="mx-auto max-w-4xl"><a href="{{ route('student.dashboard', ['month' => $slot->starts_at->format('Y-m'), 'date' => $slot->starts_at->format('Y-m-d')]) }}" class="text-sm font-semibold text-amber-700">← カレンダーに戻る</a><div class="mt-4 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p class="text-sm font-semibold tracking-widest text-amber-700">RESERVATION DETAIL</p><h1 class="mt-1 text-2xl font-bold sm:text-3xl">予約詳細</h1></div><span class="self-start rounded-full px-3 py-1 text-sm font-bold {{ $statusClass }}">{{ $statusLabel }}</span></div>
@if ($errors->any())<div class="mt-5 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800">{{ $errors->first() }}</div>@endif
<section class="mt-6 rounded-2xl border border-stone-200 bg-white p-5 shadow-sm sm:p-7"><strong class="text-xl sm:text-2xl">{{ $slot->starts_at->format('Y年n月j日 H:i') }}〜{{ $slot->ends_at->format('H:i') }}</strong><dl class="mt-5 grid gap-4 text-sm sm:grid-cols-2"><div><dt class="text-stone-500">講師</dt><dd class="mt-1 font-semibold">{{ $slot->teacherProfile->display_name }}</dd></div><div><dt class="text-stone-500">会場</dt><dd class="mt-1 font-semibold">{{ $slot->venue?->name ?? '会場未定' }}</dd></div><div><dt class="text-stone-500">コース</dt><dd class="mt-1 font-semibold">{{ $slot->course?->name ?? 'コース指定なし' }}</dd></div><div><dt class="text-stone-500">予約状態</dt><dd class="mt-1 font-semibold">{{ $statusLabel }}</dd></div></dl>@if ($reservationRequest->staff_note)<p class="mt-5 rounded-xl bg-stone-50 p-3 text-sm">先生から：{{ $reservationRequest->staff_note }}</p>@endif</section>

@if ($reservationRequest->attendanceNotice)<section class="mt-5 rounded-2xl border {{ $reservationRequest->attendanceNotice->type->value === 'absence' ? 'border-red-200 bg-red-50' : 'border-orange-200 bg-orange-50' }} p-5"><h2 class="font-bold">{{ $reservationRequest->attendanceNotice->type->value === 'absence' ? 'お休み連絡済み' : '遅刻連絡済み' }}</h2>@if ($reservationRequest->attendanceNotice->late_minutes)<p class="mt-2 text-sm">遅刻予定：{{ $reservationRequest->attendanceNotice->late_minutes }}分</p>@endif @if ($reservationRequest->attendanceNotice->expected_arrival_at)<p class="mt-1 text-sm">到着予定：{{ $reservationRequest->attendanceNotice->expected_arrival_at->format('H:i') }}</p>@endif @if ($reservationRequest->attendanceNotice->notes)<p class="mt-2 text-sm">備考：{{ $reservationRequest->attendanceNotice->notes }}</p>@endif</section>@endif

@if ($reservationRequest->status->value === 'approved' && $slot->ends_at->isFuture())
<section class="mt-6"><h2 class="text-xl font-bold">お休み・遅刻を連絡</h2><p class="mt-1 text-sm text-stone-500">再送信すると同じ予約の連絡内容を更新します。</p><div class="mt-3 grid gap-4 lg:grid-cols-2">
    <form method="post" action="{{ route('student.attendance-notices.store', $reservationRequest) }}" class="rounded-2xl border border-red-200 bg-white p-5 shadow-sm">@csrf @method('put')<input type="hidden" name="type" value="absence"><h3 class="font-bold text-red-700">お休み連絡</h3><label class="mt-4 grid gap-2 text-sm font-semibold">備考（任意）<textarea name="notes" rows="3" maxlength="1000" class="rounded-xl border border-stone-300 p-3">{{ $reservationRequest->attendanceNotice?->type?->value === 'absence' ? $reservationRequest->attendanceNotice->notes : '' }}</textarea></label><button class="mt-4 min-h-12 w-full rounded-xl bg-red-600 font-bold text-white">お休みを連絡する</button></form>
    <form method="post" action="{{ route('student.attendance-notices.store', $reservationRequest) }}" class="rounded-2xl border border-orange-200 bg-white p-5 shadow-sm">@csrf @method('put')<input type="hidden" name="type" value="late"><h3 class="font-bold text-orange-700">遅刻連絡</h3><div class="mt-4 grid gap-3 sm:grid-cols-2"><label class="grid gap-2 text-sm font-semibold">遅刻予定分数<input type="number" name="late_minutes" min="1" max="180" value="{{ $reservationRequest->attendanceNotice?->late_minutes }}" class="min-h-12 rounded-xl border border-stone-300 px-3"></label><label class="grid gap-2 text-sm font-semibold">到着予定時刻<input type="time" name="expected_arrival_time" value="{{ $reservationRequest->attendanceNotice?->expected_arrival_at?->format('H:i') }}" class="min-h-12 rounded-xl border border-stone-300 px-3"></label></div><label class="mt-3 grid gap-2 text-sm font-semibold">備考（任意）<textarea name="notes" rows="3" maxlength="1000" class="rounded-xl border border-stone-300 p-3">{{ $reservationRequest->attendanceNotice?->type?->value === 'late' ? $reservationRequest->attendanceNotice->notes : '' }}</textarea></label><button class="mt-4 min-h-12 w-full rounded-xl bg-orange-500 font-bold text-white">遅刻を連絡する</button></form>
</div></section>
@endif

<section class="mt-6 grid gap-3 sm:grid-cols-2">
    @if ($reservationRequest->status->value === 'approved' && now()->lessThanOrEqualTo($reservationRequest->transferRequestDeadline()))<a href="{{ route('student.transfer-requests.create', $reservationRequest) }}" class="inline-flex min-h-12 items-center justify-center rounded-xl border border-violet-300 bg-white px-5 font-bold text-violet-800">振替を申請する</a>@endif
    @if (in_array($reservationRequest->status->value, ['pending', 'approved'], true) && $slot->starts_at->isFuture())<form method="post" action="{{ route('student.reservations.destroy', $reservationRequest) }}" class="rounded-2xl border border-red-200 bg-white p-4">@csrf @method('delete')<label class="grid gap-2 text-sm font-semibold">キャンセル理由（任意）<input name="cancellation_reason" maxlength="500" class="min-h-11 rounded-xl border border-stone-300 px-3"></label><button onclick="return confirm('この予約をキャンセルしますか？')" class="mt-3 min-h-12 w-full rounded-xl border border-red-300 font-bold text-red-700">予約をキャンセル</button></form>@endif
</section>

@if ($reservationRequest->transferRequests->isNotEmpty() || $reservationRequest->resultingTransferRequest)<section class="mt-6 rounded-2xl border border-violet-200 bg-violet-50 p-5"><h2 class="font-bold text-violet-900">振替情報</h2>@foreach ($reservationRequest->transferRequests as $transfer)<p class="mt-2 text-sm">希望先：{{ $transfer->requestedLessonSlot->starts_at->format('Y年n月j日 H:i') }}・{{ ['pending' => '申請中', 'approved' => '確定', 'rejected' => '却下'][$transfer->status->value] }}</p>@endforeach @if ($reservationRequest->resultingTransferRequest)<p class="mt-2 text-sm">この予約は振替で確定しました。</p>@endif</section>@endif
</div>
@endsection
