@extends('layouts.app')
@section('title', '契約内容の変更 | MUSAKO')
@section('content')
@php($weekdays = ['日曜日','月曜日','火曜日','水曜日','木曜日','金曜日','土曜日'])
<div class="mx-auto max-w-5xl"><a href="{{ route('student.dashboard') }}" class="text-sm font-semibold text-amber-700">← マイページに戻る</a><div class="mt-4"><p class="text-sm font-semibold tracking-widest text-amber-700">CONTRACT</p><h1 class="mt-1 text-2xl font-bold sm:text-3xl">契約内容のお手続き</h1><p class="mt-2 text-sm text-stone-600">承認されるまでは現在の契約内容は変わりません。</p></div>
@if ($errors->any())<div class="mt-5 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800">{{ $errors->first() }}</div>@endif
<section class="mt-6"><h2 class="text-xl font-bold">現在の契約</h2><div class="mt-3 grid gap-4 lg:grid-cols-2">@forelse ($enrollments as $enrollment)<article class="min-w-0 rounded-2xl border border-stone-200 bg-white p-5 shadow-sm"><div class="flex flex-wrap items-center justify-between gap-2"><strong class="text-lg">{{ $enrollment->course->name }}</strong><span class="rounded-full bg-emerald-100 px-3 py-1 text-xs font-bold text-emerald-800">契約中</span></div><dl class="mt-4 grid grid-cols-2 gap-3 text-sm"><div><dt class="text-stone-500">曜日</dt><dd class="mt-1 font-semibold">{{ $enrollment->weekday === null ? '未設定' : $weekdays[$enrollment->weekday] }}</dd></div><div><dt class="text-stone-500">時間</dt><dd class="mt-1 font-semibold">{{ $enrollment->starts_at_time ? mb_substr($enrollment->starts_at_time, 0, 5).'〜' : '未設定' }}</dd></div><div><dt class="text-stone-500">月回数</dt><dd class="mt-1 font-semibold">{{ $enrollment->monthly_lesson_limit ? $enrollment->monthly_lesson_limit.'回' : '未設定' }}</dd></div><div><dt class="text-stone-500">レッスン時間</dt><dd class="mt-1 font-semibold">{{ $enrollment->lesson_minutes ? $enrollment->lesson_minutes.'分' : '未設定' }}</dd></div><div><dt class="text-stone-500">担当講師</dt><dd class="mt-1 font-semibold">{{ $enrollment->teacherProfile?->display_name ?? '未設定' }}</dd></div><div><dt class="text-stone-500">会場</dt><dd class="mt-1 font-semibold">{{ $enrollment->venue?->name ?? '未設定' }}</dd></div></dl></article>@empty<div class="rounded-2xl border border-dashed border-stone-300 bg-white p-8 text-center text-sm text-stone-500 lg:col-span-2">現在有効な契約がありません。</div>@endforelse</div></section>
<section class="mt-8 rounded-2xl border border-stone-200 bg-white p-5 shadow-sm sm:p-7" id="application-form"><div class="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p class="text-xs font-semibold tracking-widest text-amber-700">APPLICATION</p><h2 class="mt-1 text-xl font-bold">{{ $selectedType->label() }}</h2></div><select onchange="location.href=this.value" class="min-h-11 max-w-full rounded-xl border border-stone-300 bg-white px-3 text-sm">@foreach (App\Enums\ContractChangeType::cases() as $type)<option value="{{ route('student.contract-change-requests.index', ['type' => $type->value]) }}" @selected($selectedType === $type)>{{ $type->label() }}</option>@endforeach</select></div>
<form method="post" action="{{ route('student.contract-change-requests.store') }}" class="mt-5 grid gap-4 sm:grid-cols-2">@csrf<input type="hidden" name="type" value="{{ $selectedType->value }}">
@if ($selectedType !== App\Enums\ContractChangeType::CourseAdd)<label class="grid gap-2 text-sm font-semibold sm:col-span-2">変更する契約<select name="lesson_enrollment_id" required class="min-h-12 min-w-0 rounded-xl border border-stone-300 bg-white px-3"><option value="">選択してください</option>@foreach ($enrollments as $enrollment)<option value="{{ $enrollment->id }}" @selected(old('lesson_enrollment_id') == $enrollment->id)>{{ $enrollment->course->name }}（{{ $enrollment->venue?->name ?? '会場未設定' }}）</option>@endforeach</select></label>@endif
@if ($selectedType === App\Enums\ContractChangeType::Schedule)<label class="grid gap-2 text-sm font-semibold">希望曜日<select name="weekday" required class="min-h-12 rounded-xl border border-stone-300 bg-white px-3">@foreach ($weekdays as $value => $label)<option value="{{ $value }}" @selected(old('weekday') == $value)>{{ $label }}</option>@endforeach</select></label><label class="grid gap-2 text-sm font-semibold">希望開始時間<input type="time" name="starts_at_time" value="{{ old('starts_at_time', '18:00') }}" required class="min-h-12 rounded-xl border border-stone-300 px-3"></label>
@elseif ($selectedType === App\Enums\ContractChangeType::MonthlyLessons)<label class="grid gap-2 text-sm font-semibold sm:col-span-2">希望する月回数<input type="number" name="monthly_lesson_limit" min="1" max="31" value="{{ old('monthly_lesson_limit', 4) }}" required class="min-h-12 rounded-xl border border-stone-300 px-3"></label>
@elseif ($selectedType === App\Enums\ContractChangeType::LessonMinutes)<label class="grid gap-2 text-sm font-semibold sm:col-span-2">希望するレッスン時間（分）<input type="number" name="lesson_minutes" min="15" max="180" step="5" value="{{ old('lesson_minutes', 60) }}" required class="min-h-12 rounded-xl border border-stone-300 px-3"></label>
@elseif (in_array($selectedType, [App\Enums\ContractChangeType::CourseChange, App\Enums\ContractChangeType::CourseAdd], true))<label class="grid gap-2 text-sm font-semibold sm:col-span-2">希望コース<select name="course_id" required class="min-h-12 rounded-xl border border-stone-300 bg-white px-3"><option value="">選択してください</option>@foreach ($courses as $course)<option value="{{ $course->id }}" @selected(old('course_id') == $course->id)>{{ $course->name }}</option>@endforeach</select></label>
@elseif ($selectedType === App\Enums\ContractChangeType::VenueChange)<label class="grid gap-2 text-sm font-semibold sm:col-span-2">希望会場<select name="venue_id" required class="min-h-12 rounded-xl border border-stone-300 bg-white px-3"><option value="">選択してください</option>@foreach ($venues as $venue)<option value="{{ $venue->id }}" @selected(old('venue_id') == $venue->id)>{{ $venue->name }}</option>@endforeach</select></label>
@elseif ($selectedType === App\Enums\ContractChangeType::LessonType)<label class="grid gap-2 text-sm font-semibold sm:col-span-2">希望するレッスン種別<select name="lesson_type" required class="min-h-12 rounded-xl border border-stone-300 bg-white px-3">@foreach (App\Enums\LessonType::cases() as $lessonType)<option value="{{ $lessonType->value }}" @selected(old('lesson_type') === $lessonType->value)>{{ $lessonType->label() }}</option>@endforeach</select></label><label class="grid gap-2 text-sm font-semibold">レギュラー希望曜日<select name="weekday" class="min-h-12 rounded-xl border border-stone-300 bg-white px-3"><option value="">フレックスでは未選択</option>@foreach ($weekdays as $value => $label)<option value="{{ $value }}">{{ $label }}</option>@endforeach</select></label><label class="grid gap-2 text-sm font-semibold">レギュラー希望開始時間<input type="time" name="starts_at_time" class="min-h-12 rounded-xl border border-stone-300 px-3"></label>
@elseif ($selectedType === App\Enums\ContractChangeType::PricingCategory)<label class="grid gap-2 text-sm font-semibold sm:col-span-2">希望する料金区分<select name="pricing_category" required class="min-h-12 rounded-xl border border-stone-300 bg-white px-3">@foreach (App\Enums\PricingCategory::cases() as $category)<option value="{{ $category->value }}" @selected(old('pricing_category') === $category->value)>{{ $category->label() }}</option>@endforeach</select></label>@endif
<label class="grid gap-2 text-sm font-semibold">希望適用日<input type="date" name="effective_on" value="{{ old('effective_on', today()->addMonth()->startOfMonth()->format('Y-m-d')) }}" min="{{ today()->addDay()->format('Y-m-d') }}" required class="min-h-12 rounded-xl border border-stone-300 px-3"></label><label class="grid gap-2 text-sm font-semibold">備考（任意）<textarea name="student_note" rows="3" maxlength="1000" class="rounded-xl border border-stone-300 p-3">{{ old('student_note') }}</textarea></label><button class="min-h-12 rounded-xl bg-stone-900 px-5 font-bold text-white sm:col-span-2">この内容で申請する</button></form></section>
<section class="mt-8"><h2 class="text-xl font-bold">申請履歴</h2><div class="mt-3 grid gap-3">@forelse ($requests as $changeRequest) @php($classes = ['pending'=>'bg-amber-100 text-amber-900','approved'=>'bg-emerald-100 text-emerald-800','rejected'=>'bg-red-100 text-red-800'][$changeRequest->status->value])<article class="min-w-0 rounded-2xl border border-stone-200 bg-white p-4 shadow-sm"><div class="flex flex-wrap items-center justify-between gap-2"><strong>{{ $changeRequest->type->label() }}</strong><span class="rounded-full px-3 py-1 text-xs font-bold {{ $classes }}">{{ ['pending'=>'申請中','approved'=>'承認済み','rejected'=>'却下'][$changeRequest->status->value] }}</span></div><p class="mt-2 text-sm text-stone-600">希望適用日：{{ $changeRequest->effective_on->format('Y年n月j日') }}　申請：{{ $changeRequest->requested_at->format('Y年n月j日 H:i') }}</p>@if ($changeRequest->rejection_reason)<p class="mt-2 break-words rounded-xl bg-red-50 p-3 text-sm text-red-800">却下理由：{{ $changeRequest->rejection_reason }}</p>@endif</article>@empty<p class="rounded-2xl border border-dashed border-stone-300 bg-white p-8 text-center text-sm text-stone-500">申請履歴はありません。</p>@endforelse</div></section></div>
@endsection
